// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaglcXf_5PRRAbFGOXoSb2Z1m5Gbg1QGQ',
    appId: '1:844946150160:android:c0baef427c7cc853a1cb95',
    messagingSenderId: '844946150160',
    projectId: 'expense-tracker-assignme-f186a',
    storageBucket: 'expense-tracker-assignme-f186a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2IS7g9rQTx6XtZBSCieCCR3JHbotHq54',
    appId: '1:844946150160:ios:bea1b3afd16e30d9a1cb95',
    messagingSenderId: '844946150160',
    projectId: 'expense-tracker-assignme-f186a',
    storageBucket: 'expense-tracker-assignme-f186a.firebasestorage.app',
    iosClientId: '844946150160-k9a8q4t0re6u1ias4pb5vorq9s7tiei3.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerCipherschoolAssignment',
  );
}
